Docker 4
Otus-DevOps-2018-09/GidMaster_microservices pull request #4
Opened 2018-12-31 10:56 UTC by GidMaster

# Выполнено ДЗ № 4

 - [x] Основное ДЗ
 - [x] Задание со *

## В процессе сделано:
 - Cоздан `docker-compose.yml` для деплоя приложения. Применены переменные среды для конфигурирования параметров деплоя.
 - Получено представление о работе сетей в docker. 

## Как запустить проект:
 - N/A

## Как проверить работоспособность:
 - Сообщения об успашном завершении тестов в Travis CI.

## PR checklist
 - [x] Выставил label с номером домашнего задания
 - [x] Выставил label с темой домашнего задания

2019-01-05 15:26 UTC, ujhgj requested changes
Есть только один вопрос по docker-compose.override.yml, всё остальное хорошо

2019-01-05 15:26 UTC, ujhgj commented on src/docker-compose.override.yml
> +#    volumes:
Почему тут закомментирована секция volumes?

2019-01-06 05:59 UTC, GidMaster commented on src/docker-compose.override.yml
> +#    volumes:
Забыл снять "#" комментарии. Когда отлаживал процесс копирования исходного кода для задания со "*".

2019-01-06 05:59 UTC, GidMaster commented on src/docker-compose.override.yml
> +#    volumes:
Снял комментарии.

2019-01-06 09:41 UTC, ujhgj approved these changes

2019-01-07 06:48 UTC, merged