Gitlab ci 1
Otus-DevOps-2018-09/GidMaster_microservices pull request #5
Opened 2019-01-02 17:25 UTC by GidMaster

# Выполнено ДЗ №5

 - [x] Основное ДЗ
 - [x] Задание со *

## В процессе сделано:
 - Создан GitLab-CI сервер.
 - Добавлен раннер.
 - Настроен Pipeline.
 - Добавлены простые тесты.
 - Настроена интеграуия со Slack
 - Сделан autoscalling на основе docker-machine. (сейчас выключен)

## Как запустить проект:
 - NA/

## Как проверить работоспособность:
 - нотификации об учпешном прохождении тестов в Slcack.
 - Посмотреть инсталяцию можно  https://35.205.162.242 otus-guest/otus-guest9012

## PR checklist
 - [x] Выставил label с номером домашнего задания
 - [x] Выставил label с темой домашнего задания

2019-01-04 20:45 UTC, ujhgj commented
> Посмотреть инсталяцию можно https://35.205.162.242
уже сменился айпишник?

2019-01-04 20:52 UTC, ujhgj requested changes
Константин, не могу у вас найти пункт касательно автоматизации развёртывания раннера.

И еще, приложите пожалуйста ссылку на канал в слаке, с которым настроена автоматизация.

2019-01-05 05:53 UTC, GidMaster commented
> уже сменился айпишник?
К сожалению, я уже удалил инстанс.

2019-01-05 05:57 UTC, GidMaster commented
> Константин, не могу у вас найти пункт касательно автоматизации развёртывания раннера.

Я попробовал. развренуть схему с автоскелингом на основе docker+machine. Она работает, но я удалил его сместе с инстансом. Я очень хочу догнать группу. Давайте опустим задание со звёздочкой.  Я готов на то, что задание будет принято без звёздочки.

2019-01-05 05:58 UTC, GidMaster commented
> И еще, приложите пожалуйста ссылку на канал в слаке, с которым настроена автоматизация.

https://devops-team-otus.slack.com/messages/CDA7K36UR

2019-01-05 15:19 UTC, ujhgj approved these changes
Ок. Если захотите, сможете вернуться к заданию позже. Пока принимаю основную часть задания

2019-01-06 06:00 UTC, GidMaster commented
> Ок. Если захотите, сможете вернуться к заданию позже. Пока принимаю основную часть задания.

Отлично. Спасибо за понимание.

2019-01-06 06:00 UTC, merged